<a href="https://colab.research.google.com/github/zijierongjay/MSSP607/blob/main/Assignments/Assignment%201/Untitled5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import statsmodels.api as se
import seaborn as sns
import datetime as dt
from sklearn.linear_model import LinearRegression
from scipy import stats
from io import StringIO
import itertools

pd.set_eng_float_format(accuracy=3, use_eng_prefix=True)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

from google.colab import userdata
import os

github_token = userdata.get('Git_Key')
owner = 'zijierongjay' # Replace with the GitHub repository owner
repository = 'MSSP607' # Replace with the GitHub repository name

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directoGit_HUBry to: {os.getcwd()}")

Changed directoGit_HUBry to: /content/MSSP607

In [2]:
import pandas as pd

In [3]:
file_name = 'data/data_academic_performance.xlsx'

#excel_file = pd.ExcelFile(file_name)

#excel_file.sheet_names

In [4]:
df = pd.read_excel(
    file_name,
    sheet_name='SABER11_SABERPRO'
)

df.head()

,COD_S11,GENDER,EDU_FATHER,EDU_MOTHER,OCC_FATHER,OCC_MOTHER,STRATUM,SISBEN,PEOPLE_HOUSE,Unnamed: 9,...,CC_PRO,ENG_PRO,WC_PRO,FEP_PRO,G_SC,PERCENTILE,2ND_DECILE,QUARTILE,SEL,SEL_IHE
0,SB11201210000129,F,Incomplete Professional Education,Complete technique or technology,Technical or professional level employee,Home,Stratum 4,It is not classified by the SISBEN,Three,NaN,...,71,93,79,181,180,91,5,4,2,2
1,SB11201210000137,F,Complete Secundary,Complete professional education,Entrepreneur,Independent professional,Stratum 5,It is not classified by the SISBEN,Three,NaN,...,86,98,78,201,182,92,5,4,4,4
2,SB11201210005154,M,Not sure,Not sure,Independent,Home,Stratum 2,Level 2,Five,NaN,...,18,43,22,113,113,7,1,1,1,1
3,SB11201210007504,F,Not sure,Not sure,Other occupation,Independent,Stratum 2,It is not classified by the SISBEN,Three,NaN,...,76,80,48,137,157,67,4,3,2,2
4,SB11201210007548,M,Complete professional education,Complete professional education,Executive,Home,Stratum 4,It is not classified by the SISBEN,One,NaN,...,98,100,71,189,198,98,5,4,4,2

In [5]:
df.shape

(12411, 45)

In [6]:
df.columns

Index(['COD_S11', 'GENDER', 'EDU_FATHER', 'EDU_MOTHER', 'OCC_FATHER',
       'OCC_MOTHER', 'STRATUM', 'SISBEN', 'PEOPLE_HOUSE', 'Unnamed: 9',
       'INTERNET', 'TV', 'COMPUTER', 'WASHING_MCH', 'MIC_OVEN', 'CAR', 'DVD',
       'FRESH', 'PHONE', 'MOBILE', 'REVENUE', 'JOB', 'SCHOOL_NAME',
       'SCHOOL_NAT', 'SCHOOL_TYPE', 'MAT_S11', 'CR_S11', 'CC_S11', 'BIO_S11',
       'ENG_S11', 'Cod_SPro', 'UNIVERSITY', 'ACADEMIC_PROGRAM', 'QR_PRO',
       'CR_PRO', 'CC_PRO', 'ENG_PRO', 'WC_PRO', 'FEP_PRO', 'G_SC',
       'PERCENTILE', '2ND_DECILE', 'QUARTILE', 'SEL', 'SEL_IHE'],
      dtype='object')

In [7]:
numerical_description = pd.read_excel(
    file_name,
    sheet_name='Description of Numerical'
)

numerical_description.head(20)

,Table 1. Description of numeric variables.,Unnamed: 1
0,Variable,Full name
1,MAT_S11,Mathematics
2,CR_S11,Critical Reading
3,CC_S11,Citizen Competencies S11
4,BIO_S11,Biology
5,ENG_S11,English
6,QR_PRO,Quantitative Reasoning
7,CR_PRO,Critical Reading
8,CC_PRO,Citizen Competencies SPRO
9,ENG_PRO,English
10,WC_PRO,Written Communication
11,FEP_PRO,Formulation of Engineering Projects
12,G_SC,Global Score
13,PERCENTILE,Percentile
14,2ND_DECILE,Second Decile
15,QUARTILE,Quartile
16,SEL,Socioeconomic Level
17,SEL_IHE,Socioeconomic Level of The Institution of High...
18,NaN,NaN
19,Note: S_11 corresponds to the secondary test a...,NaN

1. Does parental education influence outcomes, and if so, how much?

In [8]:
categorical_description = pd.read_excel(
    file_name,
    sheet_name='Description of Categorical'
)

categorical_description.head(30)

,Table 2. Description of categorical variables.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Variable,Full Name,Levels,Variable,Full name,Levels
1,GENDER,Gender,2,DVD,DVD,2
2,EDU_FATHER,Father's education,12,FRESH,Fresh,2
3,EDU_MOTHER,Mother's education,12,PHONE,Phone,2
4,OCC_FATHER,Father's occupation,13,MOBILE,Mobile,2
5,OCC_MOTHER,Mother's occupation,13,REVENUE,Revenue,3
6,STRATUM,Stratum,7,JOB,Job,8
7,SISBEN,Sisben,6,SCHOOL_NAME,School name,3.73
8,PEOPLE_HOUSE,People in the house,13,SCHOOL_NAT,Nature of School,2
9,INTERNET,Internet,2,SCHOOL_TYPE,Type of School,4
10,TV,TV,2,COD_SPRO,Code Saber Pro,12.41
11,COMPUTER,Computer,2,UNIVERSITY,University,134
12,WASHING_MCH,Washing machine,2,ACADEMIC_PROGRAM,Academic Program,23
13,MIC_OVEN,Microwave oven,2,COD_S11,Code Saber 11,12.41
14,CAR,Car,2,NaN,NaN,NaN

In [9]:
df.EDU_FATHER.value_counts()

EDU_FATHER
Complete professional education          3016
Complete Secundary                       2843
Complete technique or technology         1194
Incomplete Secundary                     1091
Postgraduate education                   1085
Complete primary                          824
Incomplete primary                        735
Incomplete Professional Education         425
Not sure                                  407
0                                         391
Incomplete technical or technological     277
Ninguno                                   123
Name: count, dtype: int64

In [10]:
df.EDU_MOTHER.value_counts()

EDU_MOTHER
Complete Secundary                       3106
Complete professional education          3059
Complete technique or technology         1495
Incomplete Secundary                     1056
Postgraduate education                    997
Complete primary                          713
Incomplete primary                        541
Incomplete Professional Education         502
0                                         388
Incomplete technical or technological     341
Not sure                                  179
Ninguno                                    34
Name: count, dtype: int64

In [11]:
father_score = df.groupby('EDU_FATHER').G_SC.mean()

father_score.sort_values(ascending=False)

EDU_FATHER
Postgraduate education                  176.99
Complete professional education         167.77
Incomplete Professional Education       166.92
Complete technique or technology        164.03
Incomplete technical or technological   162.10
Not sure                                160.29
Complete Secundary                      158.79
Ninguno                                 156.63
Incomplete Secundary                    156.54
Incomplete primary                      155.73
Complete primary                        155.20
0                                       155.08
Name: G_SC, dtype: float64

In [12]:
father_score_clean = father_score.drop(
    index=['Not sure', 0],
    errors='ignore'
)

father_score_clean.sort_values(ascending=False)

EDU_FATHER
Postgraduate education                  176.99
Complete professional education         167.77
Incomplete Professional Education       166.92
Complete technique or technology        164.03
Incomplete technical or technological   162.10
Complete Secundary                      158.79
Ninguno                                 156.63
Incomplete Secundary                    156.54
Incomplete primary                      155.73
Complete primary                        155.20
Name: G_SC, dtype: float64

In [13]:
highest_father_score = father_score_clean.max()
lowest_father_score = father_score_clean.min()

difference_father = highest_father_score - lowest_father_score

print("Highest average score:", highest_father_score)
print("Lowest average score:", lowest_father_score)
print("Difference:", difference_father)

Highest average score: 176.9852534562212
Lowest average score: 155.19538834951456
Difference: 21.78986510670663

In [14]:
mother_score = df.groupby('EDU_MOTHER').G_SC.mean()

mother_score.sort_values(ascending=False)

EDU_MOTHER
Postgraduate education                  175.64
Complete professional education         168.85
Incomplete Professional Education       166.69
Complete technique or technology        163.24
Incomplete technical or technological   161.88
Not sure                                159.41
Complete Secundary                      158.47
Incomplete Secundary                    155.67
Complete primary                        155.34
0                                       154.93
Incomplete primary                      154.85
Ninguno                                 149.71
Name: G_SC, dtype: float64

In [15]:
mother_score_clean = mother_score.drop(
    index=['Not sure', 0],
    errors='ignore'
)

mother_score_clean.sort_values(ascending=False)

EDU_MOTHER
Postgraduate education                  175.64
Complete professional education         168.85
Incomplete Professional Education       166.69
Complete technique or technology        163.24
Incomplete technical or technological   161.88
Complete Secundary                      158.47
Incomplete Secundary                    155.67
Complete primary                        155.34
Incomplete primary                      154.85
Ninguno                                 149.71
Name: G_SC, dtype: float64

In [16]:
highest_mother_score = mother_score_clean.max()
lowest_mother_score = mother_score_clean.min()

difference_mother = highest_mother_score - lowest_mother_score

print("Highest average score:", highest_mother_score)
print("Lowest average score:", lowest_mother_score)
print("Difference:", difference_mother)

Highest average score: 175.63691073219658
Lowest average score: 149.7058823529412
Difference: 25.931028379255395

Parental education appears to be associated with student performance. Students whose fathers had postgraduate education had an average global score of about 176.99, compared with about 155.20 for the lowest valid group, a difference of about 21.79 points. For mothers, the difference between the highest and lowest education groups was about 25.93 points. Overall, students with more highly educated parents tended to have higher global scores.

2. Which groups/stratum performs best? Are there differences between groups/stratums? Explain your analysis.

In [17]:
df.STRATUM.value_counts()

STRATUM
Stratum 3    4045
Stratum 2    4029
Stratum 1    1709
Stratum 4    1578
Stratum 5     633
Stratum 6     403
0              14
Name: count, dtype: int64

In [18]:
stratum_score = df.groupby('STRATUM').G_SC.mean()

stratum_score.sort_values(ascending=False)

STRATUM
Stratum 6   181.51
Stratum 5   177.39
Stratum 4   172.00
Stratum 3   163.82
Stratum 2   158.20
0           154.00
Stratum 1   152.35
Name: G_SC, dtype: float64

In [19]:
stratum_score_clean = stratum_score.drop(
    index=[0],
    errors='ignore'
)

stratum_score_clean.sort_values(ascending=False)

STRATUM
Stratum 6   181.51
Stratum 5   177.39
Stratum 4   172.00
Stratum 3   163.82
Stratum 2   158.20
Stratum 1   152.35
Name: G_SC, dtype: float64

In [20]:
highest_stratum_score = stratum_score_clean.max()
lowest_stratum_score = stratum_score_clean.min()

difference_stratum = highest_stratum_score - lowest_stratum_score

print("Highest average score:", highest_stratum_score)
print("Lowest average score:", lowest_stratum_score)
print("Difference:", difference_stratum)

Highest average score: 181.51116625310175
Lowest average score: 152.3528379169105
Difference: 29.15832833619126

In [21]:
stratum_summary = df.groupby('STRATUM').G_SC.describe()

stratum_summary

            count   mean   std    min    25%    50%    75%    max
STRATUM
0           14.00 154.00 21.32 116.00 142.00 152.50 167.00 196.00
Stratum 1 1709.00 152.35 21.94  77.00 138.00 152.00 167.00 220.00
Stratum 2 4029.00 158.20 22.28  72.00 143.00 158.00 174.00 237.00
Stratum 3 4045.00 163.82 21.69  75.00 149.00 164.00 179.00 247.00
Stratum 4 1578.00 172.00 21.47  91.00 158.00 174.00 188.00 243.00
Stratum 5  633.00 177.39 21.54  37.00 165.00 179.00 192.00 246.00
Stratum 6  403.00 181.51 21.88  91.00 170.00 184.00 194.50 242.00

Stratum 6 performs best, with an average global score of about 181.51, while Stratum 1 has the lowest average score at about 152.35. The difference between the highest and lowest groups is about 29.16 points. The mean and median scores both increase steadily from Stratum 1 to Stratum 6, suggesting a clear relationship between stratum and academic performance. The standard deviations are similar across groups, so the main difference appears to be in the overall score level rather than variability.

3. How does each gender perform in the global assessment?

In [22]:
df.GENDER.value_counts()

GENDER
M    7368
F    5043
Name: count, dtype: int64

In [23]:
gender_score = df.groupby('GENDER').G_SC.mean()

gender_score

GENDER
F   161.28
M   163.69
Name: G_SC, dtype: float64

In [24]:
gender_summary = df.groupby('GENDER').G_SC.describe()

gender_summary

         count   mean   std   min    25%    50%    75%    max
GENDER
F      5043.00 161.28 22.33 76.00 146.00 162.00 177.00 242.00
M      7368.00 163.69 23.58 37.00 147.00 164.00 180.00 247.00

In [25]:
female_score = gender_score.loc['F']
male_score = gender_score.loc['M']

difference_gender = male_score - female_score

print("Female average score:", female_score)
print("Male average score:", male_score)
print("Difference:", difference_gender)

Female average score: 161.2782074162205
Male average score: 163.69082519001086
Difference: 2.4126177737903447

Male students performed slightly better in the global assessment. The average global score for males was about 163.69, while the average for females was about 161.28. The difference was about 2.41 points. The median score was also slightly higher for males, 164 compared with 162 for females. The standard deviations were similar, so the overall score distributions were fairly similar between the two groups.

4. Use your analysis to understand the results.  What did you find interesting, and can you make any recommendations or inferences?

In [26]:
print("Father education difference:", difference_father)
print("Mother education difference:", difference_mother)
print("Stratum difference:", difference_stratum)
print("Gender difference:", difference_gender)

Father education difference: 21.78986510670663
Mother education difference: 25.931028379255395
Stratum difference: 29.15832833619126
Gender difference: 2.4126177737903447

I found that socioeconomic background and parental education were more strongly associated with global scores than gender. The difference between Stratum 6 and Stratum 1 was about 29.16 points, which was the largest difference in my analysis. Parental education also showed noticeable differences, while the gender difference was only about 2.41 points. This suggests that students' social and family backgrounds may be related to academic performance. One recommendation would be to provide more academic support and educational resources to students from lower socioeconomic groups. However, these results only show associations, so we cannot conclude that these factors directly cause the differences in scores.

Additional Analysis of Student Academic Performance

In [27]:
gender_subjects = df.groupby('GENDER')[
    ['QR_PRO', 'CR_PRO', 'CC_PRO', 'ENG_PRO', 'WC_PRO', 'FEP_PRO', 'G_SC']
].mean()

gender_subjects

        QR_PRO  CR_PRO  CC_PRO  ENG_PRO  WC_PRO  FEP_PRO   G_SC
GENDER
F        71.89   61.34   58.57    66.53   56.62   145.30 161.28
M        81.20   62.79   59.61    68.16   51.71   145.60 163.69

In [28]:
stratum_subjects = df.groupby('STRATUM')[
    ['QR_PRO', 'CR_PRO', 'CC_PRO', 'ENG_PRO', 'WC_PRO', 'FEP_PRO', 'G_SC']
].mean()

stratum_subjects

           QR_PRO  CR_PRO  CC_PRO  ENG_PRO  WC_PRO  FEP_PRO   G_SC
STRATUM
0           69.79   47.36   46.00    55.07   60.50   138.07 154.00
Stratum 1   70.52   53.57   50.92    50.91   49.30   142.98 152.35
Stratum 2   74.62   58.82   55.96    60.95   51.15   142.48 158.20
Stratum 3   78.34   63.86   60.15    70.62   53.04   142.20 163.82
Stratum 4   83.22   69.27   66.97    80.10   59.59   154.05 172.00
Stratum 5   86.70   71.75   69.23    87.00   63.66   160.42 177.39
Stratum 6   88.36   73.76   71.07    92.45   65.59   162.17 181.51

In [29]:
stratum_subjects_clean = stratum_subjects.drop(
    index=[0],
    errors='ignore'
)

stratum_subjects_clean

           QR_PRO  CR_PRO  CC_PRO  ENG_PRO  WC_PRO  FEP_PRO   G_SC
STRATUM
Stratum 1   70.52   53.57   50.92    50.91   49.30   142.98 152.35
Stratum 2   74.62   58.82   55.96    60.95   51.15   142.48 158.20
Stratum 3   78.34   63.86   60.15    70.62   53.04   142.20 163.82
Stratum 4   83.22   69.27   66.97    80.10   59.59   154.05 172.00
Stratum 5   86.70   71.75   69.23    87.00   63.66   160.42 177.39
Stratum 6   88.36   73.76   71.07    92.45   65.59   162.17 181.51

In [30]:
high_school_scores = df[
    ['MAT_S11', 'CR_S11', 'CC_S11', 'BIO_S11', 'ENG_S11', 'G_SC']
]

high_school_scores.corr()

         MAT_S11  CR_S11  CC_S11  BIO_S11  ENG_S11  G_SC
MAT_S11     1.00    0.61    0.59     0.76     0.59  0.64
CR_S11      0.61    1.00    0.73     0.66     0.58  0.65
CC_S11      0.59    0.73    1.00     0.66     0.55  0.63
BIO_S11     0.76    0.66    0.66     1.00     0.59  0.67
ENG_S11     0.59    0.58    0.55     0.59     1.00  0.66
G_SC        0.64    0.65    0.63     0.67     0.66  1.00

In [31]:
high_school_scores.corr().G_SC.sort_values(ascending=False)

G_SC      1.00
BIO_S11   0.67
ENG_S11   0.66
CR_S11    0.65
MAT_S11   0.64
CC_S11    0.63
Name: G_SC, dtype: float64

In [32]:
from google.colab import files

df.to_csv('academic_performance_data.csv', index=False)
files.download('academic_performance_data.csv')