<a href="https://colab.research.google.com/github/zijierongjay/MSSP607/blob/main/Modules/Week_5/Participation_Activity_Week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1a

In [26]:
from google.colab import userdata
import os
import subprocess

github_token = userdata.get('Git_Key') #Retrieve secret key for user
owner = 'zijierongjay' # Replace with the GitHub repository owner
repository = 'MSSP607' # Replace with the GitHub repository name

clone_url = f'https://x-access-token:{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP607/Repository data/Week 05 Examples/MSSP607

In [27]:
#DID NOT CLONE USED ABOVE CODE>
#from google.colab import userdata
#import os

#github_token = userdata.get('Git_Key')

#owner = 'zijierongjay'
#repository = 'MSSP607'

In [28]:
#DID NOT CLOE THE REPOSITORY: clone_url = f'https://x-access-token:{github_token}@github.com/{owner}/{repository}.git'

In [29]:
#Updated directory
os.chdir('/content/MSSP607')

print(f"Changed directory to: {os.getcwd()}")

Changed directory to: /content/MSSP607

In [30]:
os.listdir()

['Modules',
 'Adding_File_Structure.py',
 'faang.csv',
 'data',
 'faang_melted.csv',
 'WeeklyModules',
 'MSSP607',
 'Repository data',
 'CodeSamples',
 '.git',
 'Assignments']

In [31]:
os.listdir('Repository data')

['.gitkeep', 'Week 05 Examples']

In [32]:
os.listdir('Repository data/Week 05 Examples')

['aapl.csv', 'amzn.csv', 'goog.csv', 'nflx.csv', 'fb.csv', 'MSSP607']

In [33]:
%pushd "/content/MSSP607/Repository data/Week 05 Examples"

/content/MSSP607/Repository data/Week 05 Examples

['/content/MSSP607', '/content/MSSP607']

In [34]:
import os

print(os.getcwd())
os.listdir()

/content/MSSP607/Repository data/Week 05 Examples

['aapl.csv', 'amzn.csv', 'goog.csv', 'nflx.csv', 'fb.csv', 'MSSP607']

2a

In [35]:
import pandas as pd

aapl = pd.read_csv('aapl.csv')
amzn = pd.read_csv('amzn.csv')
nflx = pd.read_csv('nflx.csv')
fb = pd.read_csv('fb.csv')
goog = pd.read_csv('goog.csv')

In [36]:
aapl.head()

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

2b

In [37]:
print("AAPL:", aapl.shape)
print("AMZN:", amzn.shape)
print("NFLX:", nflx.shape)
print("FB:", fb.shape)
print("GOOG:", goog.shape)

AAPL: (251, 6)
AMZN: (251, 6)
NFLX: (251, 6)
FB: (251, 6)
GOOG: (251, 6)

2c

In [38]:
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
nflx['ticker'] = 'NFLX'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'

In [39]:
aapl.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [40]:
print(aapl.ticker.unique())
print(amzn.ticker.unique())
print(nflx.ticker.unique())
print(fb.ticker.unique())
print(goog.ticker.unique())

['AAPL']
['AMZN']
['NFLX']
['FB']
['GOOG']

2d

In [41]:
faang = pd.concat([
    fb,
    aapl,
    amzn,
    nflx,
    goog
])

faang.head()

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

In [42]:
faang.ticker.value_counts()

ticker
FB      251
AAPL    251
AMZN    251
NFLX    251
GOOG    251
Name: count, dtype: int64

2e

In [43]:
faang.to_csv('faang.csv', index=False)

print("faang.csv saved.")

faang.csv saved.

2f

In [44]:
faang = pd.read_csv('faang.csv')

faang.head()

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

In [45]:
faang.dtypes

date       object
open      float64
high      float64
low       float64
close     float64
volume      int64
ticker     object
dtype: object

In [46]:
faang['date'] = pd.to_datetime(faang['date'])
faang['volume'] = faang['volume'].astype(int)

faang.dtypes

date      datetime64[ns]
open             float64
high             float64
low              float64
close            float64
volume             int64
ticker            object
dtype: object

In [47]:
faang = faang.sort_values(
    by=['date', 'ticker']
)

faang.head(10)

           date       open       high        low      close    volume ticker
251  2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
502  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0    2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
753  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX
252  2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   AAPL
503  2018-01-03  1188.3000  1205.4900  1188.3000  1204.2000   3108793   AMZN
1    2018-01-03   181.8800   184.7800   181.3300   184.6700  16886563     FB
1005 2018-01-03  1064.3100  1086.2900  1063.2100  1082.4800   1430170   GOOG
754  2018-01-03   202.0500   206.2100   201.5000   205.0500   8591369   NFLX

2g

In [48]:
highest_volume = faang.nlargest(7, 'volume')

highest_volume

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
433 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
496 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
463 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

2h

In [49]:
faang_melted = faang.melt(
    id_vars=['date', 'ticker']
)

faang_melted.head(10)

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000
5 2018-01-03   AAPL     open   169.2521
6 2018-01-03   AMZN     open  1188.3000
7 2018-01-03     FB     open   181.8800
8 2018-01-03   GOOG     open  1064.3100
9 2018-01-03   NFLX     open   202.0500

In [50]:
from google.colab import files

In [51]:
faang_melted.to_csv('faang_melted.csv', index=False)

files.download('faang_melted.csv')

In [52]:
files.download('faang.csv')

In [53]:
import os

print(os.getcwd())

/content/MSSP607/Repository data/Week 05 Examples

In [54]:
os.listdir('/content/MSSP607/Modules')

['Week_11',
 'Week_3',
 'Week_1',
 'Week_12',
 'Week_14',
 '.gitkeep',
 'week-4',
 'Week_13',
 'Week_9',
 'Week_8',
 'Week_4',
 'Week_6',
 'Week_5',
 'Week_10',
 'Week_7',
 'Week_2']

In [55]:
os.path.exists('Modules/Week_5')

False

In [56]:
x = lambda a, b: a + b + 10

print(x(15, 10))

35

In [57]:
faang['price_range'] = faang.apply(
    lambda row: row['high'] - row['low'],
    axis=1
)

faang[['date', 'ticker', 'high', 'low', 'price_range']].head()

           date ticker       high        low  price_range
251  2018-01-02   AAPL   169.0264   166.0442       2.9822
502  2018-01-02   AMZN  1190.0000  1170.5100      19.4900
0    2018-01-02     FB   181.5800   177.5500       4.0300
1004 2018-01-02   GOOG  1066.9400  1045.2300      21.7100
753  2018-01-02   NFLX   201.6500   195.4200       6.2300

In [58]:
faang.groupby('ticker').price_range.mean().sort_values(ascending=False)

ticker
AMZN    42.999402
GOOG    24.776056
NFLX    12.037310
FB       4.312188
AAPL     3.771129
Name: price_range, dtype: float64

In [59]:
import re

notebook_path = '/content/MSSP607/Modules/Week_5/Participation_Activity_Week5.ipynb'

with open(notebook_path, 'r', encoding='utf-8') as file:
    notebook_text = file.read()

token_pattern = r'github_pat_[A-Za-z0-9_]{20,}|ghp_[A-Za-z0-9]{20,}'

tokens_found = re.findall(token_pattern, notebook_text)

print("Number of tokens found:", len(tokens_found))

cleaned_text = re.sub(
    token_pattern,
    '[REDACTED]',
    notebook_text
)

with open(notebook_path, 'w', encoding='utf-8') as file:
    file.write(cleaned_text)

print("Notebook cleaned.")

Number of tokens found: 0
Notebook cleaned.

In [60]:
with open(notebook_path, 'r', encoding='utf-8') as file:
    notebook_text = file.read()

token_found = bool(
    re.search(
        r'github_pat_[A-Za-z0-9_]{20,}|ghp_[A-Za-z0-9]{20,}',
        notebook_text
    )
)

print("Token still found:", token_found)

Token still found: False

In [61]:
!git add "Modules/Week_5/Participation_Activity_Week5.ipynb"

warning: could not open directory 'Repository data/Week 05 Examples/Modules/Week_5/': No such file or directory
fatal: pathspec 'Modules/Week_5/Participation_Activity_Week5.ipynb' did not match any files

In [62]:
!git commit --amend --no-edit

Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@683786f05609.(none)')

In [63]:
!git push origin main

warning: redirecting to https://github.com/zijierongjay/MSSP607.git/
Everything up-to-date