<a href="https://colab.research.google.com/github/zijierongjay/MSSP607/blob/main/Modules/Week_6/PARTICIPATION_ACTIVITY_Week_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import userdata
import subprocess

github_token = userdata.get('Git_Key')

owner = 'zijierongjay'
repository = 'MSSP607'

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

subprocess.run(
    ['git', 'clone', clone_url],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

print("Repository cloned successfully.")

Repository cloned successfully.

In [4]:
import os

os.listdir('/content')

['.config', 'MSSP607', 'sample_data']

In [5]:
import os

os.chdir('/content/MSSP607')

print(os.getcwd())

/content/MSSP607

In [6]:
os.listdir('Modules/Week_6')

['.gitkeep', 'Student Performance Data.csv']

In [7]:
import pandas as pd

df = pd.read_csv(
    'Modules/Week_6/Student Performance Data.csv'
)

df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [8]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'math score', 'reading score', 'writing score', 'total score',
       'test preparation course', 'admission prospect'],
      dtype='object')

In [9]:
df['total score'].describe()

count    1000.000000
mean      203.312000
std        42.771978
min        27.000000
25%       175.000000
50%       205.000000
75%       233.000000
max       300.000000
Name: total score, dtype: float64

In [10]:
new_df = df.copy()

new_df['performance level'] = new_df['total score'].apply(
    lambda x: 'High' if x >= 233
    else 'Medium' if x >= 175
    else 'Low'
)

new_df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,performance level
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,Medium
1,female,group C,some college,standard,69,90,88,247,completed,high,High
2,female,group B,master's degree,standard,90,95,93,278,none,high,High
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,Low
4,male,group C,some college,standard,76,78,75,229,none,high,Medium

In [11]:
new_df['performance level'].value_counts()

performance level
Medium    499
High      254
Low       247
Name: count, dtype: int64

In [12]:
new_df[
    ['gender', 'total score', 'performance level']
].head(10)

   gender  total score performance level
0  female          218            Medium
1  female          247              High
2  female          278              High
3    male          148               Low
4    male          229            Medium
5  female          232            Medium
6  female          275              High
7    male          122               Low
8    male          195            Medium
9  female          148               Low

In [13]:
result_df = new_df[
    ['gender', 'total score', 'performance level']
]

result_df.head()

   gender  total score performance level
0  female          218            Medium
1  female          247              High
2  female          278              High
3    male          148               Low
4    male          229            Medium